#!/usr/bin/env python3
"""Validate the canonical workflow and synchronize generated consumers."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


SKILL_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = Path(__file__).resolve().parents[4]
SOURCE = SKILL_ROOT / "config" / "workflow.json"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated files differ from the canonical configuration.",
    )
    return parser.parse_args()


def load_and_validate() -> dict:
    config = json.loads(SOURCE.read_text(encoding="utf-8"))
    stages = config.get("stages", [])
    if len(stages) != 7:
        raise ValueError("workflow.json must define exactly seven stages")

    defaults = config.get("stateDefaults", {})
    stage_ids: set[str] = set()
    question_ids: set[str] = set()
    for stage in stages:
        stage_id = stage["id"]
        if stage_id in stage_ids:
            raise ValueError(f"duplicate stage id: {stage_id}")
        stage_ids.add(stage_id)
        if not stage.get("questions"):
            raise ValueError(f"stage has no questions: {stage_id}")
        for question in stage["questions"]:
            question_id = question["id"]
            if question_id in question_ids:
                raise ValueError(f"duplicate question id: {question_id}")
            question_ids.add(question_id)
            if question["kind"] == "field" and question["key"] not in defaults:
                raise ValueError(
                    f"unknown state field {question['key']} in {question_id}"
                )
            if (
                question["kind"] == "collection"
                and question["collection"] not in defaults
            ):
                raise ValueError(
                    f"unknown collection {question['collection']} in {question_id}"
                )

    checklist_ids = [item["id"] for item in config["checklist"]["items"]]
    if len(checklist_ids) != len(set(checklist_ids)):
        raise ValueError("checklist item ids must be unique")

    action_ids = [action["id"] for action in config["ai"]["actions"]]
    if len(action_ids) != len(set(action_ids)):
        raise ValueError("AI action ids must be unique")
    return config


def generated_outputs(config: dict) -> dict[Path, str]:
    canonical = json.dumps(config, ensure_ascii=False, indent=2)
    digest = hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:12]
    banner = f"Generated from workflow.json · sha256:{digest}"

    browser = (
        f"// {banner}. Do not edit.\n"
        f"window.ZXL_PRD_CONFIG = {canonical};\n"
    )
    worker = (
        f"// {banner}. Do not edit.\n"
        f"export const SKILL_CONFIG = {canonical};\n"
    )

    reference_lines = [
        "<!-- Generated by scripts/sync_workflow.py. Do not edit. -->",
        "",
        "# Generated workbench workflow",
        "",
        f"- Configuration version: `{config['version']}`",
        f"- Source digest: `{digest}`",
        "- Navigation: linear within each stage",
        "",
    ]
    for index, stage in enumerate(config["stages"], start=1):
        reference_lines.extend(
            [
                f"## {index}. {stage['short']}",
                "",
                stage["description"],
                "",
            ]
        )
        for question_index, question in enumerate(stage["questions"], start=1):
            required = " (required)" if question.get("required") else ""
            reference_lines.append(
                f"{question_index}. `{question['id']}` — {question['title']}{required}"
            )
        reference_lines.append("")

    reference_lines.extend(["## AI actions", ""])
    for action in config["ai"]["actions"]:
        reference_lines.append(f"- `{action['id']}` — {action['label']}")
    reference_lines.append("")

    return {
        REPO_ROOT / "workbench" / "skill-config.js": browser,
        REPO_ROOT / "worker" / "src" / "skill-config.js": worker,
        SKILL_ROOT / "references" / "workflow.generated.md": "\n".join(
            reference_lines
        ),
    }


def main() -> int:
    args = parse_args()
    config = load_and_validate()
    outputs = generated_outputs(config)
    stale: list[Path] = []

    for path, content in outputs.items():
        if path.is_file() and path.read_text(encoding="utf-8") == content:
            continue
        if args.check:
            stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"Updated: {path.relative_to(REPO_ROOT)}")

    if stale:
        for path in stale:
            print(f"STALE: {path.relative_to(REPO_ROOT)}")
        print("Run: python3 .cursor/skills/zxl-prd/scripts/sync_workflow.py")
        return 1

    print("Workflow configuration is valid and synchronized.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
